### ISSUE TITLE
전체적인 피드백

### ISSUE THREAD

**Issue by boy672820** [Jinhjlog/concurrency#1]
## 피드백

 1. 아키텍처 개선 포인트 by DI, OCP & 레이어드 아키텍처 위배 사례 ([링크](https://github.com/Jinhjlog/concurrency/blob/da2b20180a761d4d59e8bf65a946cee4b09479f7/src/modules/lecture/lecture.controller.ts#L45))
 2. 비즈니스 로직에 대한 이해 ([코드](https://github.com/Jinhjlog/concurrency/blob/da2b20180a761d4d59e8bf65a946cee4b09479f7/src/modules/lecture/lecture.service.ts#L122))
 3. 핸들링되고 있지 않은 에러 ([코드](https://github.com/Jinhjlog/concurrency/blob/da2b20180a761d4d59e8bf65a946cee4b09479f7/src/modules/lecture/database/lecture-application.repository.ts#L44))
 4. SRP 위배 사례 ([코드](https://github.com/Jinhjlog/concurrency/blob/da2b20180a761d4d59e8bf65a946cee4b09479f7/src/modules/lecture/database/lecture-application.repository.ts#L44))

### 1. 아키텍처 개선 포인트

몇 가지 개선 포인트와 레이어드 아키텍처에서 위배되는 사항에 대한 내용입니다.

#### 문제점

 - 레이어드 아키텍처를 따르고 있는 걸로 보임, 가장 문제가 되는 부분은 영속성 계층이 프레젠테이션 계층을 의존하고 있음

#### 개선 포인트

 1. 객체간의 구현 정보를 알고 있는 부분 ([코드](https://github.com/Jinhjlog/concurrency/blob/da2b20180a761d4d59e8bf65a946cee4b09479f7/src/modules/lecture/database/lecture-application.repository.ts#L44))
 2. Service가 Repository에 의존하고 있음, 이러한 구조의 트레이드오프는 비즈니스 로직이 보호될 수 없음
 3. Repository를 DI해야 하는 이유에 대해서 생각해보고, 그렇게 된다면 OCP를 어떻게 적용해볼 수 있을지? (DI와 OCP에 연관성에 대해서도 생각해보면 Best)

### 2. 비즈니스 로직에 대한 이해

 - 비즈니스 로직에 대한 이해가 아직 부족함, 도메인 vs 서비스 차이점에 대해서 알아야 함

### 3. 핸들링되고 있지 않은 에러

```typescript
async createWithUpdateLectureByOptimisticLock(
  LectureApplication: LectureApplication,
  Lecture: Lecture,
  tx: Prisma.TransactionClient,
): Promise<void> {
  await tx.lectureApplication.create({
    data: LectureApplicationMapper.toPersistence(LectureApplication),
  });

  const updatedLecture = await tx.lecture.updateMany({
    where: { id: Lecture.id, updatedAt: Lecture.updatedAt },
    data: { ...LectureMapper.toPersistence(Lecture), updatedAt: new Date() },
  });

  if (updatedLecture.count === 0) {
    throw new Error('Conflict detected');
  }
}
```

이건 너무 대 놓고 나 버그임하는 거라..

만약, 특강 업데이트 쿼리에서 특강을 찾을 수 없을 경우가 발생한다면 무조건 에러가 발생하는 거죠.

> 그럴 일이 없다고 생각하신다면?
> 이걸 기술 부채라고 부르지 않을까,

**Comment by Jinhjlog** [comment]
피드백 감사합니다.
다시 작성하겠습니다.
